config/routes.rb
Rails.application.routes.draw do
  
  mount RailsClientLogger::Engine, :at => "logger"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  
  root 'cities#index'
  

  get 'instagram' => 'campaign#instagram'
  get 'twitter' => 'campaign#twitter'
  get 'facebook' => 'campaign#facebook'
  get 'hello' => 'campaign#cp01'
  get 'ahoy' => 'campaign#cp02'

  get 'mission' => 'static_pages#mission'
  get 'payment' => 'static_pages#payment'
  get 'team' => 'static_pages#team'
  get 'terms' => 'static_pages#terms'

  get 'base' => 'base#index'
  get 'tags' => 'tags#index'
  get 'languages' => 'languages#index'
  

  get 'auth/facebook/callback' => 'auths#facebook' 
  

  get 'dashboard' => 'dashboards#index'
  get 'dashboard/reviews' => 'dashboards#review'
  get 'dashboard/offers' => 'dashboards#offer'
  get 'dashboard/orders' => 'dashboards#order'
  get 'dashboard/transaction' => 'dashboards#transaction'
  post 'dashboard/tours/:id/reviews' => 'dashboards#review'
  
  
  resources :users, only: [:create, :edit, :show, :update, :destroy] do
  end
  
  resources :sessions, only: [:create] do
    collection do 
      delete 'logout'
      get 'confirm_email'      
      get 'request_new_password'
      post 'send_reset_token'
      get 'set_new_password'
      post 'reset_password'
    end
  end
  

  resources :destinations, only: [:create] do 
    collection do 
      post 'foursquare'
      post 'google'
    end
  end

  resources :charges, only: [:create] do 
  end

  resources :cities, param: :city_name_id, only: [:show, :create] do
    member do 
      get 'locals'
    end
    collection do 
      get 'locals_locations'
    end
  end

  
  resources :tours, only: [:create, :new, :show, :update, :destroy] do
    resources :offers, only: [:create, :show, :update, :destroy] do 
      member do
        post 'message'
        post 'review'
        get 'cancel'
      end
    end
  end

  
  
end

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:index] do
        collection do
          get 'facebook'
          get 'email'
        end
      end
      resources :users, only: [:index, :show] do
      end
      resources :tours, only: [:index] do
      end
      resources :offers, only: [:index] do
      end
      resources :charges, only: [:index] do
      end
      resources :cities, only: [:index, :create, :update] do
      end
      resources :destinations, only: [:index, :create, :update] do
      end
    end
  end

  match "*path" => "errors#handel_404", via: [ :get, :post, :patch, :delete ]

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
   before_action  :sign_in_alert, :check_user_info

  def index
  end

  def review
  end

  def order
    @orders = Tour.where(traveler_id: current_user.id)
  end

  def offer
    @offers = Offer.includes(:tour).where(guide_id: current_user.id)
  end

  def transaction
  end

  private 
    def check_user_info
      if current_user.first_name.nil? || current_user.last_name.nil? || current_user.gender.nil? || current_user.city.nil? || current_user.city.nil? || current_user.birthday.nil? 
        redirect_to "/users/#{current_user.id}/edit"
      end
    end

    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to :back # halts request cycle
      end
    end

    def sign_in_alert
      if session_nil?
       @page_title = "User Not Logined"
       render :template => "errors/partial/session/_nil", :locals => { type: "session_nil" }
      end
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def any_review?(user_review)
    user_review.try(:length) > 0
  end

  def city_name(city_id)
    begin
      city = City.find(city_id) 
      city.try(:name)
    rescue ActiveRecord::RecordNotFound => e
      logger.warn(e)
    end
  end
end

app/views/dashboards/_layout.html.erb
<% @page_title = "Reviews - Dashboard" %>
<div class="md-col12 sm-col12 xs-col12 bg-special content-header pd-tp-100">
	<h1 class="h2 txt-center">Dashboard</h1>
</div>
<main class="main">
  <%= render partial: "dashboards/partial/nav" %>
  <div class="md-col12 sm-col12 xs-col12 cl-b bg-lightgray">
  	<!-- <section id="left-column" class="sm-hide left-col md-col4 fl-l pt-50">
  	  <div class="inner-80">
  	  	<%= render partial: "layouts/partial/profile_dashboard", locals: { user: current_user } %>
  	  </div>
  	</section> -->
<!--   
  	<section class=" sm-col12 xs-col12 fl-l bg-lightgray">
  	  <div class="inner-80">
  	  	<h2 class="h5 mt-30">Reviews</h2>
  	  	<% if current_user.reviews.any?  %>
  	  	  <% current_user.reviews.each do |review| %>
  	  	  	<%= render partial: "dashboards/partial/review", locals: { review: review } %>
  	  	  <% end %>
  	  	<% else %>
  	  	  <h4 class="h4 alert-tag">*You don't have any reviews.</h4>
  	  	<% end %>
  	  	</div>
  	  </div>
  	</section> -->
  	dksododk
  	<%= yield :profile%>
  </div>
</main>

<script>(function(e,t,s,c){var n,o,r;e.SMCX=e.SMCX||[],t.getElementById(c)||(n=t.getElementsByTagName(s),o=n[n.length-1],r=t.createElement(s),r.type="text/javascript",r.async=!0,r.id=c,r.src=["https:"===location.protocol?"https://":"http://","widget.surveymonkey.com/collect/website/js/z9yF_2FrKYbMdoREBudCXJlgOclhBFjCF8X93pvOCOaisqTeAzgD0cnArVx0sQxGCm.js"].join(""),o.parentNode.insertBefore(r,o))})(window,document,"script","smcx-sdk");</script>

app/views/dashboards/index.html.erb
<% @page_title = "Profile - Dashboard" %>
<div class="md-col12 sm-col12 xs-col12 bg-special content-header pd-tp-100">
	<h1 class="h2 txt-center">Dashboard</h1>
</div>
<main class="main">
  <%= render partial: "dashboards/partial/nav" %>
  <div class="md-col12 sm-col12 xs-col12 bg-lightgray">
  	<!-- <section id="left-column" class="sm-hide left-col md-col4 fl-l pt-50">
  	  <div class="inner-80">
  	  	<%= render partial: "layouts/partial/profile_dashboard", locals: { user: current_user } %>
  	  </div>
  	</section> -->
    <div class="inner-80">
      <div class="pv-30">
        <div class="bg-white card pv-20">
          <%= render partial: "layouts/partial/profile_image", locals: { user: current_user } %>
          <h2 class="h2 txt-center mt-5"><%= current_user.full_name %></h2>
          <h5 class="h6 txt-center"><i class="fa fa-suitcase mr-5"></i><%= current_user.work %></h5>
          <p class="txt-center mt-5"><i class="fa fa-map-marker mr-5 font-red"></i><%= city_name_from_user(  current_user) %></p>
          <p class="txt-center mt-5"><span class="mr-5"><%= current_user.age %> years old</span></p>
          <p class="txt-center mt-5"><i class="fa fa-venus-mars mr-5"></i><%= current_user.gender_s %></span></p>
          
          <% if is_current_user?(current_user.id) %>
            <p class="txt-center mt-15">
              <a href="/users/<%= current_user.id %>/edit">Edit Profile</a> |
              <%=link_to "Delete this account", user_path(current_user), :class => "link-red user-delete-confirm"%>
            </p>
          <% end %>
          <div class="md-col12">
            <ul class="txt-center member-status">
              <li class="panel-member-status">
                <p class="font-small">MEMBER SINCE</p>
                <h4 class=""><%= user_print_member_since(current_user) %></h4>
              </li>
              <li class="panel-member-status">
                <p class="font-small">REVIEWS</p>
                <h4 class=""><%= current_user.reviews_count %></h4>
              </li>
            </ul>
          </div>
  
          <div class="md-col12 pb-100">
            <div class="box-verification txt-center mt-15">
           　　<div class=" txt-center">
                <div class="line-verification txt-center sm-mt-20">
           　　    <li class="<%= print_facebook_status(current_user) %>"></li>
           　　    <li class="font-small mt-5">FACEBOOK</li>
           　　  </div>
                <div class="line-verification txt-center sm-mt-20">
           　　    <li class="<%= print_phone_status(current_user) %>"></li>
           　　    <li class="font-small mt-5">PHONE</li>
                </div>
                <div class="line-verification txt-center sm-mt-20">
           　　    <li class="<%= print_driver_license_status(current_user) %>"></li>
           　　    <li class="font-small mt-5">DRIVER ID</li>
                </div>
                <div class="line-verification txt-center sm-mt-20">
           　　    <li class="<%= print_criminal_record_status(current_user) %>"></li>
           　　    <p class="font-small mt-5">CRIMINAL</p>
           　　    <p class="font-small">RECORD</p>
                </div>
           　  <div class="cl-b"></div>
           　</div>
          </div>
          <div class="cl-b"></div>
        </div>
      </div>
      <div class="cl-b">
        <div class="pt-50">
          <label for="" class="label">INTRODUCTION</label>
          <p class="description cl-b mt-5"><%= current_user.description %></p>
        </div>
        <div class="pt-50"></div>
          <label for="" class="label txt-center">LANGUAGES</label>
          <p id="language" class="mt-5">
            <% current_user.languages.each do |lang| %>
              <%= lang.name %>
            <% end %>
          </p>
        </div>
        <div class="pt-50"></div>
          <label for="" class="label">TAGS</label>
          <p id="list-tag" class="mt-5">
            <% current_user.tags.each do |tag| %>
              <span class="tag mt-5"><%= tag.title %></span>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</main>
   
<script>(function(e,t,s,c){var n,o,r;e.SMCX=e.SMCX||[],t.getElementById(c)||(n=t.getElementsByTagName(s),o=n[n.length-1],r=t.createElement(s),r.type="text/javascript",r.async=!0,r.id=c,r.src=["https:"===location.protocol?"https://":"http://","widget.surveymonkey.com/collect/website/js/z9yF_2FrKYbMdoREBudCXJlgOclhBFjCF8X93pvOCOaisqTeAzgD0cnArVx0sQxGCm.js"].join(""),o.parentNode.insertBefore(r,o))})(window,document,"script","smcx-sdk");</script>

app/views/dashboards/offer.html.erb
<% @page_title = "Offers - Dashboard" %>
<div class="md-col12 bg-special content-header pd-tp-100">
  <h1 class="h2 txt-center">Dashboard</h1>
</div>
<main class="main">
  <%= render partial: "dashboards/partial/nav" %>
  <div class="md-col12 sm-col12 xs-col12 bg-lightgray">
    <section class="md-col12 sm-col12 xs-col12 right-col fl-l sm-pt-10 bg-lightgray">
      <div class="inner-80">
      	<h2 class="h5 mt-30">Your Offers</h2>
      	<% if @offers.any? %>
      	  <table id="table-offer" class="table table-hover mt-5">
      	    <thead class="thead">
      	      <tr>
      	        <th class="thead cell">Tour Date</th>
      	        <th class="thead cell">Title</th>
      	        <th class="thead cell">Status</th>
      	        <th class="thead cell">Offer detail</th>
      	        <th class="thead cell"></th>
      	      </tr>
      	    </thead>
      	    <tbody>
      	      <% @offers.each do |offer| %>    
      	        <tr class="tr bg-white">
      	          <td class="cell"><%= offer.tour.tour_date.strftime('%x') %></td>
      	          <td class="cell tabel-tour-title"><a href="/tours/<%= offer.tour.id %>" class=""><%= offer.tour.title %></a></td>
      	          <td id="status" class="cell <%= print_status_class_offer(offer) %>"></td>
      	          <td class="cell cell-static"><a href="/tours/<%= offer.tour.id %>/offers/<%= offer.id %>" class="btn-small-x1 shrink-btn">See Offer</a></td>
      	          <td class="cell"><a href="" class="">Edit</a> / <a href="" class="link-red delete-confirm">Delete</a></td>
      	        </tr>
      	      <% end %> 
      	    </tbody>
      	  </table>	
      	  <!-- offers and offers -->
      	<% else %>
      	  <!-- <a href="/">Search orders</a> -->
      	<% end %>
      </div>
    </section>
  </div>
</main>

app/views/dashboards/order.html.erb
<% @page_title = "Orders - Dashboard" %>
<div class="md-col12 bg-special content-header pd-tp-100">
  <h1 class="h2 txt-center">Dashboard</h1>
</div>
<main class="main">
  <%= render partial: "dashboards/partial/nav" %>
  <div class="md-col12 sm-col12 xs-col12 bg-lightgray">
  	<section class="md-col12 sm-col12 xs-col12 right-col fl-l right-col sm-pt-10 bg-lightgray">
  	  <div class="inner-80">
  	  	<h2 class="h5 mt-30">Your Orders</h2>
  	  	<% if @orders.any? %>
  	  	  <table id="table-order" class="table table-hover mt-5">
  	  	    <thead class="thead">
  	  	      <tr>
  	  	        <th class="th">Tour Date</th>
  	  	        <th class="th">Title</th>
  	  	        <th class="th">City</th>
  	  	        <th class="th">Status</th>
  	  	        <th class="th"></th>
  	  	      </tr>
  	  	    </thead>
  	  	    <tbody>
  	  	  	  <% @orders.each do |order| %>
  	  	  	    <tr class="tr bg-white">
  	  	  	      <td class="cell"><%= order.tour_date_dmy %></td>
  	  	  	      <td class="cell" class="tabel-tour-title"><a href="/tours/<%= order.id  %>" class=""><%= order.title %></a></td>
  	  	  		    <td class="cell"><%= city_name(order.city_id) %></td>
  	  	  	      <td id="status" class="cell <%= print_status_class(order) %>"></td>
  	  	  		    <td class="cell">
  	  	  	      	<% if editable?(order) %>
  	  	  		        	<a href="" class="">Edit</a> / 
  	  	  		        	<%=link_to "Delete", tour_path(order.id), :class => "link-red delete-confirm"%>
  	  	  		      <% end %>
  	  	  		    </td>
  	  	  	    </tr>
  	  	  	  <% end %> 
  	  	    </tbody>
  	  	  </table>	
  	  	  <!-- Orders and offers -->
  	  	  <% @orders.each do |order| %>
  	  	  	<% if has_any_offers?(order) %>
  	  	  	  <h3 class="h5 mt-30"><%= order.tour_date.strftime('%x') %> | 	<a href="/tours/<%= order.id %>"><%= order.title %></a></h3>
  	  	  	  <table class="table table-hover mt-5">
  	  	  	    <thead class="thead">
  	  	  	      <tr>
  	  	  	        <th class="th">Offering User</th>
  	  	  	        <th class="th"></th>
  	  	  	        <th class="th">Status</th>
  	  	  	        <th class="th">Fee</th>
  	  	  	        <th class="th"></th>
  	  	  	      </tr>
  	  	  	    </thead>
  	  	  	    <tbody>
  	  	  	      <% order.offers.each do |offer| %>
  	  	  	  	    <tr class="tr bg-white">
  	  	  	  	      <td class="cell">
                        <img src="<%= print_user_image(get_user(offer.guide_id), "small") %>" class="profile-img-xs mr-10"><%= show_first_name(get_user(offer.guide_id)) %>
                      </td>
  	  	  	  	      <td class="cell"></td>
  	  	  	  	      <td id="status" class="cell  <%= print_status_class_offer(offer)  %>"></td>
  	  	  	  	      <td class="cell" class="tabel-tour-title">$<%= offer.price %></td>
  	  	  	  	      <td class="cell"> <a href="/tours/<%= order.id %>/offers/<%= offer.id %>" class="btn-small-x1 shrink-btn">See Offer</a></td>
  	  	  	  	    </tr>
  	  	  	  	  <% end %>
  	  	  	  	<!--       <tr class="tbody bg-white">
  	  	  	  	        <td class="cell">Bob</td>
  	  	  	  	        <td class="cell"></td>
  	  	  	  	        <td id="status" class="cell progress"></td>
  	  	  	  	        <td class="cell" class="tabel-tour-title">$90</td>
  	  	  	  	        <td class="cell">-</td>
  	  	  	  	      </tr> -->
  	  	  	    </tbody>
  	  	  	  </table>	
  	  	  	<% end %>
  	  	  <% end %>
  	  	<% else %>
  	  	  <a href="/tours/new">Post your ideal tour</a>
  	  	<% end %>
  	  </div>
  	</section>
  </div>
</main>

app/views/dashboards/review.html.erb
<% @page_title = "Reviews - Dashboard" %>
<div class="md-col12 sm-col12 xs-col12 bg-special content-header pd-tp-100">
	<h1 class="h2 txt-center">Dashboard</h1>
</div>
<main class="main">
  <%= render partial: "dashboards/partial/nav" %>
  <div class="md-col12 sm-col12 xs-col12 cl-b right-col bg-lightgray">
  	<!-- <section id="left-column" class="sm-hide left-col md-col4 fl-l pt-50">
  	  <div class="inner-80">
  	  	<%= render partial: "layouts/partial/profile_dashboard", locals: { user: current_user } %>
  	  </div>
  	</section> -->
  
  	<section class="sm-col12 xs-col12 fl-l bg-lightgray">
  	  <div class="inner-80">
  	  	<h2 class="h5 mt-30">Reviews</h2>
  	  	<% if current_user.reviews.any?  %>
  	  	  <% current_user.reviews.each do |review| %>
  	  	  	<%= render partial: "dashboards/partial/review", locals: { review: review } %>
  	  	  <% end %>
  	  	<% else %>
  	  	  <h4 class="h4 alert-tag">*You don't have any reviews.</h4>
  	  	<% end %>
  	  	</div>
  	  </div>
  	</section>
  </div>
</main>

<script>(function(e,t,s,c){var n,o,r;e.SMCX=e.SMCX||[],t.getElementById(c)||(n=t.getElementsByTagName(s),o=n[n.length-1],r=t.createElement(s),r.type="text/javascript",r.async=!0,r.id=c,r.src=["https:"===location.protocol?"https://":"http://","widget.surveymonkey.com/collect/website/js/z9yF_2FrKYbMdoREBudCXJlgOclhBFjCF8X93pvOCOaisqTeAzgD0cnArVx0sQxGCm.js"].join(""),o.parentNode.insertBefore(r,o))})(window,document,"script","smcx-sdk");</script>

app/views/dashboards/transaction.html.erb
<% @page_title = "Transaction - Dashboard" %>
<div class="md-col12 bg-special content-header pd-tp-100">
  <h1 class="h2 txt-center">Dashboard</h1>
</div>
<main class="main">
  <%= render partial: "dashboards/partial/nav" %>
  <div class="md-col12 sm-col12 xs-col12 bg-lightgray">
    <section class="md-col12 sm-col12 xs-col12 right-col fl-l sm-pt-10 bg-lightgray">
      <div class="inner-80">
        <h5 class="h5 mt-30">Transaction</h5>
        <div class="mt-30"></div>
  	  	<% if current_user.charging %>
  	  	  <span class="h6 mt-30">IN</span><span class="font-small"> ( Because your offer is accepted ) </span>
  	  	  <table class="table table-hover">
  	  	    <thead class="thead">
  	  	      <tr>
  	  	        <th class="th">Tour Date</th>
  	  	        <th class="th">Title</th>
  	  	        <th class="th">User</th>
  	  	        <th class="th">Payment Day</th>
  	  	        <th class="th">Status</th>
  	  	        <th class="th">Amount</th>
  	  	      </tr>
  	  	    </thead>
  	  	    <tbody>
  	  	  	<% current_user.charging.each do |charging| %>
  	  	  	  <tr class="tr bg-white">
  	  	  	    <td class="cell"><%= charging.created_at.strftime('%x') %></td>
  	  	  	    <td class="cell" class="tabel-tour-title"><a href="/tours/<%= charging.tour_id %>/offers/<%= charging.offer_id %>" class=""><%= charging.offer.tour.title %></a></td>
  	  	  	    <td class="cell" class="tabel-tour-title">
  	  	  	    	<a href="/users/<%= get_user(charging.receiver_id).id %>" class="">
  	  	  	    		<%= get_user(charging.receiver_id).first_name %>
  	  	  	    	</a>
  	  	  	    </td>
  	  	  	    <td class="cell"><%= charging.created_at.strftime('%x') %></td>
  	  	  	    <td id="status" class="cell <%= print_status_transaction_css_class(charging) %>"></td>
  	  	  	    <td class="cell">$<%= charging.price %></td>
  	  	  	  </tr>
  	  	  	<% end %>
  	  	    </tbody>
  	  	  </table>	
  	  	<% end %>
        <div class="mt-15"></div>
  	  	<% if current_user.charging %>
  	  	  <span class="h6">OUT</span><span class="font-small"> ( Because you ordered a tour )</span>
  	  	  <table class="table table-hover">
  	  	    <thead class="thead">
  	  	      <tr>
  	  	        <th class="th">Tour Date</th>
  	  	        <th class="th">Title</th>
  	  	        <th class="th">User</th>
  	  	        <th class="th">Payment Day</th>
  	  	        <th class="th">Status</th>
  	  	        <th class="th">Amount</th>
  	  	      </tr>
  	  	    </thead>
  	  	    <tbody>
  	  	  	<% current_user.charged.each do |charged| %>
  	  	  	  <tr class="tr bg-white">
  	  	  	    <td class="cell date"><%= charged.created_at.strftime('%x') %></td>
  	  	  	    <td class="cell" class="tabel-tour-title"><a href="/tours/<%= charged.tour_id %>/offers/<%= charged.offer_id %>" class=""><%= charged.offer.tour.title %></a></td>
  	  	  	    <td class="cell" class="tabel-tour-title">
  	  	  	      <a href="/users/<%= get_user(charged.sender_id).id %>" class="">
  	  	  	    		<%= show_first_name(get_user(charged.receiver_id)) %>
  	  	  	      </a>
  	  	  	    </td>
  	  	  	    <td class="cell date"><%= charged.created_at.strftime('%x') %></td>
  	  	  	    <td id="status" class="cell <%=print_status_transaction_css_class(charged) %>"></td>
  	  	  	    <td class="cell">$<%= charged.total_price %></td>
  	  	  	  </tr>
  	  	  	<% end %>
  	  	    </tbody>
  	  	  </table>	
  	  	<% end %>
      </div>
    </div>
  </div>
</main>